/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ExperiencesPage: typeof import('./src/components/ExperiencesPage.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillsPage: typeof import('./src/components/SkillsPage.vue')['default']
    SkilsPage: typeof import('./src/components/SkilsPage.vue')['default']
    TypewriterEffect: typeof import('./src/components/TypewriterEffect.vue')['default']
  }
}
